version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - SERVICES=acm,apigateway,cloudformation,cloudwatch,config,dynamodb,dynamodbstreams,ec2,es,events,firehose,iam,kinesis,kms,lambda,logs,opensearch,redshift,resource-groups,resourcegroupstaggingapi,route53,route53resolver,s3,s3control,scheduler,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts,support,swf,transcribe
      - PERSISTENCE=1
    volumes:
      - ~/localstack/volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge
